# Generated by Django 5.1.1 on 2024-09-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='name',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
