# Generated by Django 5.1.1 on 2024-09-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_remove_userregistration_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
