# Generated by Django 5.1.1 on 2024-09-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0005_stations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='station_location',
            field=models.CharField(max_length=200),
        ),
    ]
