# Generated by Django 5.1.1 on 2024-09-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0006_alter_stations_station_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoughModel',
            fields=[
                ('itemid', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('itemname', models.CharField(max_length=50)),
                ('itemloc', models.CharField(max_length=200)),
            ],
        ),
    ]
