# Generated by Django 5.1.1 on 2024-09-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0008_delete_roughmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_location', models.CharField(max_length=100)),
                ('asset_last_location', models.CharField(max_length=100)),
                ('asset_status', models.CharField(max_length=50)),
                ('asset_type', models.CharField(max_length=50)),
                ('asset_expiry_date', models.DateField()),
            ],
        ),
    ]
