# Generated by Django 5.1.1 on 2024-09-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0009_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_expiry_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_last_location',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_location',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_status',
        ),
        migrations.AddField(
            model_name='asset',
            name='last_location',
            field=models.CharField(default='inventory', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(default='inventory', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MOVING', 'Moving'), ('MOVED', 'Moved')], default='INACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('VEHICLE', 'Vehicle'), ('WEAPON', 'Weapon'), ('ELECTRONIC', 'Electronic Device'), ('PROTECTIVE_GEAR', 'Protective Gear'), ('OFFICE_EQUIPMENT', 'Office Equipment'), ('MISC', 'Miscellaneous Equipment')], max_length=50),
        ),
    ]
