# Generated by Django 5.1.1 on 2024-09-30 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0010_rename_asset_expiry_date_asset_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='manufactured_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='asset',
            name='station_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.stations'),
        ),
        migrations.AddField(
            model_name='stations',
            name='station_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.userregistration'),
        ),
    ]
