# Generated by Django 5.1.1 on 2024-09-30 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0011_asset_manufactured_date_asset_station_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stations',
            name='station_master',
        ),
        migrations.AddField(
            model_name='stations',
            name='station_master_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.userregistration'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('VEHICLE', 'Vehicle'), ('WEAPON', 'Weapon'), ('ELECTRONIC', 'Electronic Device'), ('PROTECTIVE_GEAR', 'Protective Gear'), ('OFFICE_EQUIPMENT', 'Office Equipment'), ('MISC', 'Miscellaneous Equipment')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='station_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.stations'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MOVING', 'Moving'), ('MOVED', 'Moved')], db_index=True, default='INACTIVE', max_length=50),
        ),
    ]
