# Generated by Django 5.1.1 on 2024-09-30 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0012_remove_stations_station_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='station_master_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.userregistration'),
        ),
    ]
