# Generated by Django 5.1.1 on 2024-10-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0013_alter_stations_station_master_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.stations'),
        ),
    ]
