# Generated by Django 5.1.1 on 2024-10-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0014_userregistration_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_REPAIR', 'under_repair'), ('DECOMMISSIONED', 'Decommissioned')], db_index=True, default='INACTIVE', max_length=50),
        ),
    ]
