# Generated by Django 5.1.1 on 2024-10-10 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0015_alter_asset_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateTimeField(auto_now_add=True)),
                ('auditor_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_REPAIR', 'under_repair'), ('DECOMMISSIONED', 'Decommissioned')], max_length=50)),
                ('utilization', models.CharField(choices=[('IN_USE', 'In Use'), ('IDLE', 'Idle'), ('UNAVAILABLE', 'Unavailable')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('discrepancy', models.BooleanField(default=False)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.asset')),
            ],
        ),
    ]
