# Generated by Django 5.1.1 on 2024-10-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0016_auditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='asset_id',
            new_name='audit_log_id',
        ),
    ]
