# Generated by Django 5.1.1 on 2024-10-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0017_rename_asset_id_auditlog_audit_log_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='utilization',
            field=models.CharField(choices=[('IN_USE', 'In_Use'), ('IDLE', 'Idle'), ('UNAVAILABLE', 'Unavailable')], max_length=50),
        ),
    ]
