# Generated by Django 5.1.1 on 2024-10-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0018_alter_auditlog_utilization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='audit_log_id',
            new_name='audit_asset_id',
        ),
    ]
