# Generated by Django 5.1.1 on 2024-10-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0019_rename_audit_log_id_auditlog_audit_asset_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='audit_asset_id',
            new_name='audit_log_id',
        ),
    ]
