# Generated by Django 5.1.1 on 2024-10-15 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0020_rename_audit_asset_id_auditlog_audit_log_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_maintenance_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='total_operational_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='asset',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='maintenance_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='operational_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='AssetUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CHECKOUT', 'Checkout'), ('CHECKIN', 'Checkin'), ('TRANSFER', 'Transfer')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.userregistration')),
            ],
        ),
    ]
