# Generated by Django 5.1.1 on 2024-10-15 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0021_asset_last_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='last_maintenance_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
