# Generated by Django 5.1.1 on 2024-10-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0022_alter_asset_last_maintenance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='last_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='total_operational_hours',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='usage_count',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='maintenance_flag',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='operational_hours',
        ),
        migrations.DeleteModel(
            name='AssetUsageLog',
        ),
    ]
