# Generated by Django 5.1.1 on 2024-10-15 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0023_remove_asset_last_maintenance_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('request_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('request_date', models.DateField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.asset')),
            ],
        ),
    ]
