# Generated by Django 5.1.1 on 2024-10-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0025_assetrequest_requesting_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='requesting_station',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
