# Generated by Django 5.1.1 on 2024-10-15 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0026_alter_assetrequest_requesting_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
